apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sr7welxwu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sr7welxwu-go 
  name: sr7welxwu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sr7welxwu-go 
